-- Rollback 001_initial.sql
DROP TABLE IF EXISTS vault_snapshots CASCADE;
DROP TABLE IF EXISTS agents CASCADE;
DROP TABLE IF EXISTS vrf_requests CASCADE;
DROP TABLE IF EXISTS actions CASCADE;
DROP TABLE IF EXISTS hands CASCADE;
DROP TABLE IF EXISTS seats CASCADE;
DROP TABLE IF EXISTS poker_tables CASCADE;
DROP TABLE IF EXISTS processed_events CASCADE;
DROP TABLE IF EXISTS indexer_state CASCADE;
